name: Pull Request Tests

on: 
  workflow_dispatch:
  pull_request:
    branches: 
      - master
      - develop
      - release

jobs: 
  test:
    runs-on: macos-13
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install dependencies
      #   run: bundle install

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app # replace with your desired Xcode version

      - name: Install Dependencies (e.g., CocoaPods)
        run: |
          gem install bundler
          bundle install
          bundle exec pod install --repo-update
          pod install

      - name: Build & Test
        run: xcodebuild -workspace kitcast.xcworkspace -scheme kitcast -destination 'platform=tvOS Simulator,name=Apple TV,OS=16.1' build test

      # - name: Setup Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: latest-stable
          
      # - name: Cache Homebrew Bundler RubyGems
      #   id: cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.set-up-homebrew.outputs.gems-path }}
      #     key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
      #     restore-keys: ${{ runner.os }}-rubygems-
        
      # - name: Install Homebrew Bundler RubyGems
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     brew install-bundler-gems
      #     brew install fastlane
      #     brew install cocoapods
        
      # - name: Send Slack notification
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   run: |
      #     msg="New pull request to ${{ github.ref }} by ${{ github.actor }}"
      #     curl -X POST -H 'Content-type: application/json' --data "{'text':'$msg'}" $SLACK_WEBHOOK_URL

      # - name: Boot Apple TV Simulator
      #   run: xcrun simctl boot "Apple TV"

      # - name: Run Tests
      #   run: fastlane tests

      - name: Run Bundle Tests
        run: bundle exec fastlane tests
        
      - name: Run Slack Message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          msg='{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*New Build Triggered!* :rocket:\nBranch: *${{ github.ref }}*\nBy: *${{ github.actor }}*"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Repository: *${{ github.repository }}*\nEvent Name: *${{ github.event_name }}*"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": ":octocat: <${{ github.event.repository.html_url }}|View on GitHub>"
                  }
                ]
              }
            ]
          }'
          curl -X POST -H 'Content-type: application/json' --data "$msg" $SLACK_WEBHOOK_URL
        
